<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ovotan.Controls.Docking\Ovotan.Controls.Docking.csproj" />
    <ProjectReference Include="..\Ovotan.Windows.EndPointManagement\Ovotan.Windows.EndPointManagement.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Dialogs\" />
  </ItemGroup>

</Project>
